mkdir src
mkdir src\Workspace
mkdir src\Players
mkdir src\Lighting
mkdir src\MaterialService
mkdir src\NetworkClient
mkdir src\ReplicatedFirst
mkdir src\ReplicatedStorage
mkdir src\ServerScriptService
mkdir src\ServerStorage
mkdir src\StarterGui
mkdir src\StarterPack
mkdir src\StarterPlayer
mkdir src\StarterPlayer\StarterPlayerScripts
mkdir src\StarterPlayer\StarterCharacterScripts
mkdir src\Teams
mkdir src\SoundService
mkdir src\TextChatService