[Mar. 16, 2021]
You can now rig an existing rig for use with these faces! You don't need to use the preset rigs here anymore! :)

This also means that you can use any body scale head mesh to use with HD faces easily.

=======================================================================================================================

				---HOW TO CONVERT AN EXISTING RIG---
				1. Download and install the "HDify" Plugin by BenIsLegit (https://www.roblox.com/catalog/6486399814/HDify)

				2. Select an existing rig

				3. Press "Head"

				4. Press "Faces" to insert the faces model

=======================================================================================================================

Also, we've renamed ourselves from "ROBLOX Film & Media Community" to "ROBLOX Cinema Community" and moved to a new group if you'd like to join!

https://www.roblox.com/groups/9106786/ROBLOX-Cinema-Community#!/about